# ===============================
# SERVER
# ===============================
quarkus.http.port=8080

# ===============================
# CORS (QUARKUS 3.x)
# ===============================
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=*

# ===============================
# DATABASE
# ===============================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=root

# Migration: Update schema (Safe for data)
quarkus.hibernate-orm.database.generation=update
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/tiketing

# File Upload Limits
quarkus.http.limits.max-body-size=25M

# ===============================
# HIBERNATE ORM
# ===============================
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true

# ===============================
# SWAGGER
# ===============================
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger

mp.openapi.extensions.smallrye.info.title=Ticketing API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=Backend Ticketing System

# JWT
mp.jwt.verify.publickey.location=jwt/publicKey.pem
mp.jwt.verify.issuer=ticketing-api

smallrye.jwt.sign.key.location=jwt/privateKey.pem

# MINIO CONFIG
minio.url=http://127.0.0.1:9000
minio.access-key=R3GFy3FeAKJFMCVzB88f
minio.secret-key=T4NCq5L76JoeTUsxPUHlKueWo77aMrlgXHhnFQKO
minio.bucket=tiketingbaru

# quarkus.log.category."io.quarkus.hibernate".level=DEBUG
# quarkus.log.category."org.hibernate".level=DEBUG
# quarkus.log.category."io.agroal".level=DEBUG
quarkus.log.level=INFO