# ===============================
# SERVER
# ===============================
quarkus.http.port=8080

# ===============================
# CORS (QUARKUS 3.x)
# ===============================
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=*

# ===============================
# DATABASE
# ===============================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=root
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ticketing

# ===============================
# HIBERNATE ORM
# ===============================
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true

# ===============================
# SWAGGER
# ===============================
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger

mp.openapi.extensions.smallrye.info.title=Ticketing API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=Backend Ticketing System

# JWT
mp.jwt.verify.publickey.location=jwt/publicKey.pem
mp.jwt.verify.issuer=ticketing-api

smallrye.jwt.sign.key.location=jwt/privateKey.pem

# MINIO CONFIG
minio.url= http://192.168.0.102:9000 
minio.access-key=Ml8tC5KazXdtYlM88eKW
minio.secret-key=5mkcFSU3MlmfSgBSK6j44MvjfZtkeCcu2v8elQ9j
minio.bucket=tiketing

# quarkus.log.category."io.quarkus.hibernate".level=DEBUG
# quarkus.log.category."org.hibernate".level=DEBUG
# quarkus.log.category."io.agroal".level=DEBUG
quarkus.log.level=INFO